FAQ/urls.py
from django.urls import path
from . import views

app_name = 'FAQ'

urlpatterns = [
    path('', views.faqViews, name='faq'),
]

accmanager/urls.py
from django.urls import path

from . import views

app_name = 'accmgr'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('<int:id>', views.profile, name='profile-id'),
    path('edit', views.edit, name='edit'),
    path('edit/<int:id>', views.edit, name='edit-id'),
    path('riwayat', views.riwayat, name='riwayat'),
    path('riwayat/<int:id>', views.riwayat, name='riwayat-id'),
    path('status', views.status, name='status'),
    path('status/<int:id>', views.status, name='status-id'),
]

trashbank/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('FAQ/', views.faq, name='faq'),
    path('tutorial/', views.tutorial, name='tutorial'),
    path('profile/', include('accmanager.urls')),
    path('buangsampah/', include('buangsampah.urls')),
    path('register/', include('register.urls')),
    path('login/', include('login.urls')),
    path('logout/', include('logout.urls')),
    path('statistik/', include('statistik.urls')),
]

accmanager/models.py
from django.db import models

# Create your models here.

class Dummy(object):
    pass

class Account(models.Model):
    name = models.CharField(max_length=10485760, default='')
    job = models.CharField(max_length=10485760, default='')
    address = models.CharField(max_length=10485760, default='')
    balance = models.IntegerField(default=0)

class Riwayat(models.Model):
    owner_id = models.ForeignKey('Account', on_delete=models.CASCADE, null=True)
    jenis = models.CharField(max_length=10485760, default='')
    berat = models.IntegerField()
    lokasi = models.CharField(max_length=10485760, default='')
    diterima = models.BooleanField(default=False)
    pass

accmanager/forms.py
from django import forms
from .models import Account

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = '__all__'

accmanager/views.py
from django.shortcuts import render
from .models import Dummy, Account, Riwayat
from buangsampah.models import Sampah
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse

def snippet_to_account(snippet_query):
    _return = []
    for i in snippet_query:
        dummy = Dummy()
        dummy.berat = i.berat_Sampah
        dummy.lokasi = i.lokasi_Rumah
        dummy.jenis = '|'.join(i.kategori_Sampah)
        _return.append(dummy)
    return _return


# Create your views here.

@login_required(login_url='/login/')
def profile(request, id=None):
    link_riwayat = reverse('accmgr:riwayat')
    link_status = reverse('accmgr:status')
    link_edit = reverse('accmgr:edit')

    filtered = Account.objects.filter(id=id)
    if len(filtered) > 0:
        selaccount = filtered.first()

        selbalance = str(selaccount.balance)
        balance = '.'.join([selbalance[::-1][i:i+3] for i in range(0, len(selbalance), 3)])[::-1]
        balance = 'Rp ' + balance + ',00'
        link_riwayat = reverse('accmgr:riwayat-id', args=[selaccount.id])
        link_status = reverse('accmgr:status-id', args=[selaccount.id])
        link_edit = reverse('accmgr:edit-id', args=[selaccount.id])
    elif len(Account.objects.all()) > 0:
        selaccount = Account.objects.first()
        return HttpResponseRedirect(reverse('accmgr:profile-id', args=[selaccount.id]))
    elif id != None:
        return HttpResponseRedirect(reverse('accmgr:profile'))
    else:
        selaccount = Dummy()
        selaccount.name = 'Dummy Account'
        selaccount.job = 'Students'
        selaccount.address = 'Depok'
        selaccount.id = None
        balance = 'Rp 18.000,00'

    return render(request, 'profile.html', context={
        'selaccount' : selaccount,
        'balance' : balance,
        'link_riwayat' : link_riwayat,
        'link_status' : link_status,
        'link_edit' : link_edit,
    })

def edit(request, id=None):
    return render(request, 'edit.html')

@login_required(login_url='/login/')
def riwayat(request, id=None):
    list_riwayat = Sampah.objects.filter(owner_id=request.user.id, status_diterima=True)
    # list_riwayat = snippet_to_account(Snippet.objects.filter(status_Diterima=True))
    return render(request, 'riwayat.html', context={
        'list_riwayat' : list_riwayat,
        'owner' : request.user.id,
    })

@login_required(login_url='/login/')
def status(request, id=None):
    list_riwayat = Sampah.objects.filter(owner_id=request.user.id, status_diterima=False)
    # list_riwayat = snippet_to_account(Snippet.objects.filter(status_Diterima=False))
    return render(request, 'status.html', context={
        'list_riwayat' : list_riwayat,
        'owner' : request.user.id,
    })

accmanager/templates/edit.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
{% include 'new_navbar.html' with profile_stats='active' %}
{% endblock %}

{% block includedcss %}
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap-grid.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/profile_page.css' %}">
{% endblock %}
    
{% block content %}
<div class="header">
    <div class="container">
        <h1>EDIT</h1>
    </div>
</div>

<body>
    
    <!-- Page Content Start -->
    <form action="post">
        <!-- <div class="banner">
            <div class="text-center">
                <h2>
                    <input type="text" name="name" maxlength="2147483647" required id="id_name" value={{ selaccount.name }}>
                </h2>
                <h2>{{ selaccount.name }}</h2> -->
            <!-- </div>
        </div> -->
    
        <h3>
            <div class="row profile-info">
                <div class="col-1 col-lg-2"></div>
                <div class="col-10 col-lg-8 row">
                    <div class="col-5 col-lg-4 label">
                        Pekerjaan
                    </div>
                    <div class="col-7 col-lg-8 data">
                        {{ selaccount.job }}
                    </div>
                    <div class="col-5 col-lg-4 label">
                        Tempat Tinggal
                    </div>
                    <div class="col-7 col-lg-8 data">
                        {{ selaccount.address }}
                    </div>
                    <div class="col-5 col-lg-4 label">
                        Dompetku
                    </div>
                    <div class="col-7 col-lg-8 data">
                        <h1>{{ balance }}</h1>
                    </div>
    
                    <div class="col-12" id="card-container">
                        <a href={{ link_riwayat }}><card id="left">Riwayat</card></a>
                        <a href={{ link_status }}><card id="right">Status Sampah</card></a>
                    </div>
                </div>
                <div class="col-1 col-lg-2">
                    <img src="https://image.flaticon.com/icons/svg/1159/1159633.svg" style="height: 30px;">
                </div>
            </div>
        </h3>
    </form>
    <!-- Page Content End -->

    {% endblock %}

accmanager/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
{% include 'new_navbar.html' with profile_stats='active' %}
{% endblock %}

{% block includedcss %}
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap-grid.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/profile_page.css' %}">
{% endblock %}
    
{% block content %}
<div class="banner">
    <div class="text-center">
        <h2>{{ user.first_name }} {{ user.last_name }}</h2>
        <a href="{{ link_edit }}"><card id="edit">Edit Profile</card></a>
    </div>
</div>

<h3>
    <div class="row profile-info">
        <div class="col-1 col-lg-2"></div>
        <div class="col-10 col-lg-8 row">
            <div class="col-5 col-lg-4 label">
                Pekerjaan
            </div>
            <div class="col-7 col-lg-8 data">
                {{ selaccount.job }}
            </div>
            <div class="col-5 col-lg-4 label">
                Tempat Tinggal
            </div>
            <div class="col-7 col-lg-8 data">
                {{ selaccount.address }}
            </div>
            <div class="col-5 col-lg-4 label">
                Dompetku
            </div>
            <div class="col-7 col-lg-8 data">
                <h1>{{ balance }}</h1>
            </div>

            <div class="col-12" id="card-container">
                <a href="{{ link_riwayat }}"><card id="left">Riwayat</card></a>
                <a href="{{ link_status }}"><card id="right">Status Sampah</card></a>
            </div>
        </div>
        <div class="col-1 col-lg-2">
            <!-- <a href={{ link_edit }}><img src="https://image.flaticon.com/icons/svg/1159/1159633.svg" style="height: 30px;"></a> -->
        </div>
    </div>
</h3>
{% endblock %}

accmanager/templates/riwayat.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
{% include 'new_navbar.html' with profile_stats='active' %}
{% endblock %}

{% block includedcss %}
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap-grid.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/profile_page.css' %}">
{% endblock %}
    
{% block content %}
<div class="header">
    <div class="container">
        <h1>RIWAYAT</h1>
    </div>
</div>

<h3>
    <div class="row profile-info" style="margin-top: 5vh;">
        <div class="col-1 col-lg-2"></div>
        <div class="col-10 col-lg-8 row" style="border-top-style: solid; padding: 0px;">
            
            {% for riwayat in list_riwayat %}
            <div class="col-12 row riwayat-container">
                <div class="col-8 col-lg-6">
                    <div class="riwayat-info">
                        <div id="jenis"><h2>{{ riwayat.jenis }}</h2></div>
                        <div id="berat" style="margin-top: 10px;"><h2>{{ riwayat.berat }} Kg</h2></div>
                        <div id="lokasi" style="margin-top: 30px;"><h6>{{ riwayat.lokasi }}</h6></div>
                    </div>
                </div>
                <div class="col-4 col-lg-6">
                    <div class="status-card"><card id="left">Accepted</card></div>
                </div>
            </div>
            {% endfor %}
                

            <div class="col-12" id="card-container">
                <a href="{% url 'accmgr:profile-id' owner %}"><card id="left">Kembali</card></a>
                <a href="{% url 'accmgr:status-id' owner %}"><card id="right">Status Sampah</card></a>
            </div>
        </div>
        <div class="col-1 col-lg-2"></div>
    </div>
</h3>
{% endblock %}

accmanager/templates/status.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
{% include 'new_navbar.html' with profile_stats='active' %}
{% endblock %}

{% block includedcss %}
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap-grid.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/profile_page.css' %}">
{% endblock %}
    
{% block content %}
<div class="header">
    <div class="container">
        <h1>Status</h1>
    </div>
</div>

<h3>
    <div class="row profile-info" style="margin-top: 5vh;">
        <div class="col-1 col-lg-2"></div>
        <div class="col-10 col-lg-8 row" style="border-top-style: solid; padding: 0px;">
            
            {% for riwayat in list_riwayat %}
            <div class="col-12 row riwayat-container">
                <div class="col-8 col-lg-6">
                    <div class="riwayat-info">
                        <div id="jenis"><h2>{{ riwayat.jenis }}</h2></div>
                        <div id="berat" style="margin-top: 10px;"><h2>{{ riwayat.berat }} Kg</h2></div>
                        <div id="lokasi" style="margin-top: 30px;"><h6>{{ riwayat.lokasi }}</h6></div>
                    </div>
                </div>
                <div class="col-4 col-lg-6">
                    <div class="status-card"><card id="right">Pending</card></div>
                </div>
            </div>
            {% endfor %}

            <div class="col-12" id="card-container">
                <a href="{% url 'accmgr:profile-id' owner %}"><card id="left">Kembali</card></a>
                <a href="{% url 'accmgr:riwayat-id' owner %}"><card id="right">Riwayat</card></a>
            </div>
        </div>
        <div class="col-1 col-lg-2"></div>
    </div>
</h3>
{% endblock %}