FAQ/urls.py
from django.urls import path
from . import views

app_name = 'FAQ'

urlpatterns = [
    path('', views.faqViews, name='faq'),
]

accmanager/urls.py
from django.urls import path

from . import views

app_name = 'accmgr'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('<int:id>', views.profile, name='profile-id'),
    path('edit', views.edit, name='edit'),
    path('edit/<int:id>', views.edit, name='edit-id'),
    path('riwayat', views.riwayat, name='riwayat'),
    path('riwayat/<int:id>', views.riwayat, name='riwayat-id'),
    path('status', views.status, name='status'),
    path('status/<int:id>', views.status, name='status-id'),
]

buangsampah/urls.py
from django.urls import path
from . import views

app_name = 'buangsampah'

urlpatterns = [
    path('', views.submit_sampah, name ='buangsampah'),
]

helloworld/urls.py
from django.urls import path

from . import views

app_name = 'helloworld'

urlpatterns = [
    path('helloworld/', views.hello, name='hello'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.homeViews, name='home'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login_user, name='login'),
]

logout/urls.py
from django.urls import path
from . import views

app_name = 'logout'

urlpatterns = [
    path('', views.logout_user, name='logout_user'),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.register_user, name='register'),
]

statistik/urls.py
from django.urls import path

from . import views

app_name = 'statsk'

urlpatterns = [
    path('', views.index, name='index'),
    path('get_stats/', views.get_stats, name='get'),
]

trashbank/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('FAQ/', views.faq, name='faq'),
    path('tutorial/', views.tutorial, name='tutorial'),
    path('profile/', include('accmanager.urls')),
    path('buangsampah/', include('buangsampah.urls')),
    path('register/', include('register.urls')),
    path('login/', include('login.urls')),
    path('logout/', include('logout.urls')),
    path('statistik/', include('statistik.urls')),
]

tutorial/urls.py
from django.urls import path
from . import views

app_name = 'tutorial'

urlpatterns = [
    path('', views.tutorialViews, name='tutorial'),
]

FAQ/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

lists/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

logout/models.py
from django.db import models

# Create your models here.

statistik/models.py
from django.db import models

# Create your models here.

FAQ/views.py
from django.shortcuts import render, redirect

# Create your views here.
def faqViews(request):
    return render(request, 'FAQ.html')

home/views.py
from django.shortcuts import render, redirect

# Create your views here.
def homeViews(request):
    return render(request, 'home.html')

lists/views.py
from django.shortcuts import render

# Create your views here.

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session
from trashbank.views import home

def login_user(request):

    # prevent an account that already login accessing this page
    if 'AnonymousUser' != str(request.user):
        return redirect('home')

    message = ''

    if request.method == 'POST':

        username_login = request.POST['username']
        password_login = request.POST['password']

        user = authenticate(request, username=username_login, password=password_login)
        # print(user)

        if user != None:
            try:
                login(request, user)
            except:
                pass

            return redirect('home')

        else:
            message = 'Wrong username or password'

    context = {
        'message' : message,
    }

    return render(request, 'login.html', context)

logout/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session

@login_required(login_url='/login/')
def logout_user(request):
    if request.method == 'POST':

        # if user click the logout button
        if request.POST['logout'] == '':
            try:
                logout(request)
            except:
                pass

        return redirect('/')

    return render(request, 'logout.html')

register/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from trashbank.views import home

def register_user(request):
    # prevent an account that already login accessing this page
    if 'AnonymousUser' != str(request.user):
        return redirect(reverse(home))

    message_username = ''
    message_password = ''

    if request.method == 'POST':
        user_name       = request.POST['username']
        user_password   = request.POST['password']
        user_first_name = request.POST['first_name']
        user_last_name  = request.POST['last_name']

        # check wether the username has been used by another user
        if User.objects.filter(username=user_name).exists():
            message_username = 'Username has been used'

        # check wether username is valid
        if not username_is_valid(user_name):
            message_username = 'Invalid username'

        # check password length
        if len(user_password) < 8:
            message_password = 'Passwords must have a minimum length of 8'

        # valid input
        if len(message_username) == 0 and len(message_password) == 0:
            NewUser = User.objects.create_user(
                username    =user_name,
                password    =user_password,
                first_name  =user_first_name,
                last_name   =user_last_name
            )
            NewUser.save()

            return redirect('/login/')

    context = {
        'message_username': message_username,
        'message_password': message_password,
    }

    return render(request, 'register.html', context)


# method for validating username
def username_is_valid(username):
    for c in username:
        if not (c.isalnum() or c in '_.'):
            return False

    return True

statistik/views.py
from django.http import JsonResponse
from django.shortcuts import render
from buangsampah.models import Sampah

# Create your views here.
def index(request):
    context = {}

    return render(request, 'statistik/index.html', context)

def get_stats(request):
    if request.method == 'POST':
        query = Sampah.objects.all()
        if 'lokasi_id' in request.POST:
            lokasi_id = request.POST['lokasi_id']
            query = query.filter(lokasi_id__regex=rf'^{lokasi_id}.{{{10 - len(lokasi_id)}}}$')

    query = [i.__dict__.copy() for i in query]
    for i in query: del i['_state']

    return JsonResponse(list(query), safe=False)

tutorial/views.py
from django.shortcuts import render, redirect

# Create your views here.
def tutorialViews(request):
    return render(request, 'tutorial.html')

statistik/templates/statistik/index.html
{% extends 'base.html' %}
{% load static %}
    
{% block includedcss %}
<style>
#total-berat {
    margin-top: 40px;
}

#total-berat * {
    margin-top: auto;
    margin-bottom: auto;
    margin-right: 20px;
}

th div {
    margin-top: 20px;
}
</style>
{% endblock includedcss %}

{% block includedscript %}
<script src="{% static 'bngsampah/js/buang.js' %}"></script>

<script>
function onSubmit(params) {
    let select_provinsi = $('select#id_nama_provinsi');
    let select_kota = $('select#id_nama_kota');
    let select_kec = $('select#id_nama_kecamatan');
    let select_desa = $('select#id_nama_desa');
    let total_berat_container = $('#total-berat');
    let total_berat_field = $('#total-berat-field');
    let kategori_berat_field = {
        'Plastik' : $('#total-plastik-field'),
        'Kertas' : $('#total-kertas-field'),
        'Sisa Makanan' : $('#total-sisa-field'),
        'Logam' : $('#total-logam-field'),
        'Kaca' : $('#total-kaca-field'),
        'Lain-lain' : $('#total-lain-field'),
    };

    let lokasi_id = ''
    if (select_provinsi.val() != 'none') {
        lokasi_id = select_provinsi.val();
    }
    if (select_kota.val() != 'none') {
        lokasi_id = select_kota.val();
    }
    if (select_kec.val() != 'none') {
        lokasi_id = select_kec.val();
    }
    if (select_desa.val() != 'none') {
        lokasi_id = select_desa.val();
    }

    $.post(
        '/statistik/get_stats/',
        {'csrfmiddlewaretoken' : $('[name="csrfmiddlewaretoken"]').val(), 'lokasi_id' : lokasi_id},
        function (data, status) {
            console.log(data);
            let total_berat = 0;
            let kategori_berat = {
                'Plastik' : 0,
                'Kertas' : 0,
                'Sisa Makanan' : 0,
                'Logam' : 0,
                'Kaca' : 0,
                'Lain-lain' : 0,
            };
            data.forEach(element => {
                total_berat += element.berat_sampah;
                kategori_berat[element.kategori_sampah[0]] += element.berat_sampah;
            });
            console.log(total_berat);
            total_berat_container.css({
                'display' : 'flex'
            });
            total_berat_field.text(`${total_berat} kg`);

            for (const kategori in kategori_berat) {
                kategori_berat_field[kategori].text(`${kategori_berat[kategori]} kg`);
            }
        }
    );
    return false;
}
</script>
{% endblock includedscript %}
        
<!-- Navigation Bar -->
{% block navbar %}
{% include 'new_navbar.html' with statistik_stats='active' %}
{% endblock navbar %}

{% block content %}
<div class="header">
    <div class="container">
        <h1>Info Sampah</h1>
    </div>
</div>

<div class="centerized-div" style="margin: 50px 0px;">
    <div>
        <form action="{% url 'statsk:get' %}" onsubmit="return onSubmit();">
            {% csrf_token %}
            <div>
                <h2>Provinsi</h2>
                <select class="select-lokasi" name="nama_provinsi" id="id_nama_provinsi">
                    <option value="none">--</option>
                </select>
            </div>
            <div id="kota-selector">
                <h2>Kota / Kabupaten</h2>
                <select class="select-lokasi" name="nama_kota" id="id_nama_kota" disabled>
                    <option value="none">--</option>
                </select>
            </div>
            <div id="kecamatan-selector">
                <h2>Kecamatan</h2>
                <select class="select-lokasi" name="nama_kecamatan" id="id_nama_kecamatan" disabled>
                    <option value="none">--</option>
                </select>
            </div>
            <div id="desa-selector">
                <h2>Kelurahan / Desa</h2>
                <select class="select-lokasi" name="lokasi_id" id="id_nama_desa" disabled>
                    <option value="none">--</option>
                </select>
            </div>
    
            <div style="margin-top: 20px;">
                <input type="submit" value="Search">
            </div>
        </form>
    
        <div id="total-berat" style="" class="centerized-div">
            <table>
                <tr>
                    <th><div style="width: 20vw;"><h2>Total Berat</h2></div></th>
                    <td><div style="width: 50vw;"><h4 id="total-berat-field"></h4></div></td>
                <tr>
                    <th><div style="width: 20vw;"><h2>Plastik</h2></div></th>
                    <td><div style="width: 50vw;"><h4 id="total-plastik-field"></h4></div></td>
                </tr>
                <tr>
                    <th><div style="width: 20vw;"><h2>Kertas</h2></div></th>
                    <td><div style="width: 50vw;"><h4 id="total-kertas-field"></h4></div></td>
                </tr>
                <tr>
                    <th><div style="width: 20vw;"><h2>Sisa Makanan</h2></div></th>
                    <td><div style="width: 50vw;"><h4 id="total-sisa-field"></h4></div></td>
                </tr>
                <tr>
                    <th><div style="width: 20vw;"><h2>Logam</h2></div></th>
                    <td><div style="width: 50vw;"><h4 id="total-logam-field"></h4></div></td>
                </tr>
                <tr>
                    <th><div style="width: 20vw;"><h2>Kaca</h2></div></th>
                    <td><div style="width: 50vw;"><h4 id="total-kaca-field"></h4></div></td>
                </tr></div>
                <tr>
                    <th><div style="width: 20vw;"><h2>Lain-lain</h2></div></th>
                    <td><div style="width: 50vw;"><h4 id="total-lain-field"></h4></div></td>
                </tr>
            </table>
            <!-- <h2>Total Berat : </h2><h2 id="total-berat-field"></h2> -->
        </div>
    </div>
</div>
{% endblock content %}
    