FAQ/urls.py
from django.urls import path
from . import views

app_name = 'FAQ'

urlpatterns = [
    path('', views.faqViews, name='faq'),
]

accmanager/urls.py
from django.urls import path

from . import views

app_name = 'accmgr'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('<int:id>', views.profile, name='profile-id'),
    path('edit', views.edit, name='edit'),
    path('edit/<int:id>', views.edit, name='edit-id'),
    path('riwayat', views.riwayat, name='riwayat'),
    path('riwayat/<int:id>', views.riwayat, name='riwayat-id'),
    path('status', views.status, name='status'),
    path('status/<int:id>', views.status, name='status-id'),
]

buangsampah/urls.py
from django.urls import path
from . import views

app_name = 'buangsampah'

urlpatterns = [
    path('', views.submit_sampah, name ='buangsampah'),
]

helloworld/urls.py
from django.urls import path

from . import views

app_name = 'helloworld'

urlpatterns = [
    path('helloworld/', views.hello, name='hello'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.homeViews, name='home'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login_user, name='login'),
]

logout/urls.py
from django.urls import path
from . import views

app_name = 'logout'

urlpatterns = [
    path('', views.logout_user, name='logout_user'),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.register_user, name='register'),
]

statistik/urls.py
from django.urls import path

from . import views

app_name = 'statsk'

urlpatterns = [
    path('', views.index, name='index'),
    path('get_stats/', views.get_stats, name='get'),
]

trashbank/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('FAQ/', views.faq, name='faq'),
    path('tutorial/', views.tutorial, name='tutorial'),
    path('profile/', include('accmanager.urls')),
    path('buangsampah/', include('buangsampah.urls')),
    path('register/', include('register.urls')),
    path('login/', include('login.urls')),
    path('logout/', include('logout.urls')),
    path('statistik/', include('statistik.urls')),
]

tutorial/urls.py
from django.urls import path
from . import views

app_name = 'tutorial'

urlpatterns = [
    path('', views.tutorialViews, name='tutorial'),
]

FAQ/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

lists/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

logout/models.py
from django.db import models

# Create your models here.

FAQ/views.py
from django.shortcuts import render, redirect

# Create your views here.
def faqViews(request):
    return render(request, 'FAQ.html')

home/views.py
from django.shortcuts import render, redirect

# Create your views here.
def homeViews(request):
    return render(request, 'home.html')

lists/views.py
from django.shortcuts import render

# Create your views here.

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session
from trashbank.views import home

def login_user(request):

    # prevent an account that already login accessing this page
    if 'AnonymousUser' != str(request.user):
        return redirect('home')

    message = ''

    if request.method == 'POST':

        username_login = request.POST['username']
        password_login = request.POST['password']

        user = authenticate(request, username=username_login, password=password_login)
        # print(user)

        if user != None:
            try:
                login(request, user)
            except:
                pass

            return redirect('home')

        else:
            message = 'Wrong username or password'

    context = {
        'message' : message,
    }

    return render(request, 'login.html', context)

logout/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session

@login_required(login_url='/login/')
def logout_user(request):
    if request.method == 'POST':

        # if user click the logout button
        if request.POST['logout'] == '':
            try:
                logout(request)
            except:
                pass

        return redirect('/')

    return render(request, 'logout.html')

register/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from trashbank.views import home

def register_user(request):
    # prevent an account that already login accessing this page
    if 'AnonymousUser' != str(request.user):
        return redirect(reverse(home))

    message_username = ''
    message_password = ''

    if request.method == 'POST':
        user_name       = request.POST['username']
        user_password   = request.POST['password']
        user_first_name = request.POST['first_name']
        user_last_name  = request.POST['last_name']

        # check wether the username has been used by another user
        if User.objects.filter(username=user_name).exists():
            message_username = 'Username has been used'

        # check wether username is valid
        if not username_is_valid(user_name):
            message_username = 'Invalid username'

        # check password length
        if len(user_password) < 8:
            message_password = 'Passwords must have a minimum length of 8'

        # valid input
        if len(message_username) == 0 and len(message_password) == 0:
            NewUser = User.objects.create_user(
                username    =user_name,
                password    =user_password,
                first_name  =user_first_name,
                last_name   =user_last_name
            )
            NewUser.save()

            return redirect('/login/')

    context = {
        'message_username': message_username,
        'message_password': message_password,
    }

    return render(request, 'register.html', context)


# method for validating username
def username_is_valid(username):
    for c in username:
        if not (c.isalnum() or c in '_.'):
            return False

    return True

templates/base.html
{% load static %}
<!doctype html>

<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Added CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <!-- FAVICON -->
    <link rel="shortcut icon" type="image/png" href="{% static 'img/Logo 3.png' %}" />
    {% block includedcss %}
        
    {% endblock %}
    
    <!-- Head Script -->
    {% block includedscript %}
        
    {% endblock %}
        
    <!-- FONT -->
    <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">

    <title>
    {% block title %}
        TRASH-IT
    {% endblock %}
        </title>
</head>

<body>
    {% block bodystart %}
    
    {% endblock bodystart %}
    
    <!-- Navigation Bar -->
    {% block navbar %}
        
    {% endblock %}
        
    
    <!-- Page Content Start -->
    <div id="content">
        {% block content %}
            
        {% endblock %}
    </div>
    <!-- Page Content End -->



    <!-- Optional JavaScript -->
    <!-- Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

    <!-- ajax -->
    <script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
    
    
    {% block bodyend %}
        
    {% endblock %}
        
</body>

</html>

templates/new_faq.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
{% include 'new_navbar.html' with faq_stats='active' %}
{% endblock %}

{% block includedcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_faq.css' %}">
{% endblock %}
    
{% block content %}
<div class="header">
    <div class="container">
        <h1>FAQs</h1>
    </div>
</div>

<div class="container faq-block">
    <div class="faq-content">
        <h2>Kemana uang bayaran saya masuk?</h2>
        <p>
            Bayaran akan dikirim ke <strong style="color: #155E63;">Dompetku</strong> anda sesuai dengan
            tarif yang telah ditentukan oleh mitra kami berdasarkan jenis sampah
            dan berat sampah yang anda berikan
        </p>
    </div>

    <div class="faq-content">
        <h2>Bagaimana cara saya mendaftar sebagai mitra?</h2>
        <p>
            Jika anda adalah pemilik bank sampah, anda dapat mendaftarkan usaha anda
            dengan mengirim email ke <strong style="color: #155E63;">example@trash-it.com</strong> atau menghubung kami
            ke <strong style="color:#155E63">021 - 72911</strong>
        </p>
    </div>

    <div class="faq-content">
        <h2>
            Bagaimana jika sampah yang ingin saya buang
            tidak terdaftar di pilihan kategori sampah?
        </h2>
        <p>
            Anda dapat memilih pilihan lain-lain di list kategori sampah. Mitra kami akan
            menentukan harga yang tepat bagi jenis sampah yang ingin anda buang
        </p>
    </div>

    <div class="faq-content">
        <h2>Bagaimana cara menggunakan aplikasi ini?</h2>
        <p>
            Silahkan kunjungi <span><a href="/tutorial" style="color:#76B39D">Tutorial</a></span>
        </p>
    </div>
</div>
{% endblock %}
    

templates/new_home.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
{% include 'new_navbar.html' with home_stats='active' %}
{% endblock %}
    
{% block includedcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_home.css' %}">
{% endblock %}
    
{% block content %}
<div class="container">
  <h1 class="welcome">WELCOME!</h1>
</div>
<div clas="box">
    <div class="contentA">
            <h1 class="apaitu">APA ITU</h1>
            <h1 class="trashit">TRASH-IT <span><a style="color: black;">?</a></span></h1>
            <p class="desc-apa">
                Trash-IT adalah aplikasi yang akan membantu anda <br>
                dalam pembuangan sampah. Trash-It memberikan layanan <br>
                penjemputan sampah dengan bayaran sesuai dengan jenis <br>
                sampah dan berat sampah yang anda berikan ke kami. <br>
            </p>
            <img class="logo-a" src="{% static 'img/Logo 3.png' %}" alt="">
    </div>
    <div class="contentB">
        <h1 class="mengapa">MENGAPA</h1>
        <h1 class="trashit">TRASH-IT <span><a style="color: black;">?</a></span></h1>
        <div class="container-desc">
            <p class="desc-mengapa">
            • Praktis & Mudah <br>
            • Efisiensi waktu <br>
            • Ramah Lingkungan <br>
            </p>
            <img class="logo-b" src="{% static 'img/Logo 2.png' %}" alt="">
        </div>
    </div>
    <div class="tutorial text-center">
        <p class="desc-button">Pelajari Cara Memakai App Ini</p>
        <a href="{% url 'tutorial' %}">
            <button type="button" class="btn btn-primary btn-lg">TUTORIAL</button>
        </a>
        <p class="desc-button">Siap Membersihkan Bumi?</p>
        <a href="{% url 'buangsampah:buangsampah' %}">
            <button type="button" class="btn btn-primary btn-lg">SIAP!</button>
    
        </a>
    </div>
    <div>
        <h1 class="contact">CONTACT US</h1>
        <h3 class="info">
            example@trash-it.com <br>
            021-72991 <br> <br>
        </h3>
    </div>
</div>
{% endblock %}
    

templates/new_navbar.html
{% load static %}
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img style="height: auto; width: 150px;" src="{% static 'img/Logo 1.png' %}" alt="">
            </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="nav navbar-nav">
                
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class= "navbar-brand" style="color: white !important;">Hai, {{user.first_name}}</a>
                </li>
                <li class="nav-item {{ logout_stats }}">
                    <a class="nav-link" href="{% url 'logout:logout_user' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item {{ login_stats }}">
                    <a class="nav-link" href="{% url 'login:login' %}">Login</a>
                </li>
                <li class="nav-item {{ register_stats }}">
                    <a class="nav-link" href="{% url 'register:register' %}">Register</a>
                </li>
                {% endif %}
                    
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item {{ home_stats }}">
                <a class="nav-link" href="{% url 'home' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                
                {% if user.is_authenticated %}
                <li class="nav-item  {{ buangsampah_stats }}">
                <a class="nav-link" href="{% url 'buangsampah:buangsampah' %}">Buang Sampah</a>
                </li>
                {% endif %}
                    
                <li class="nav-item {{ statistik_stats }}">
                <a class="nav-link" href="{% url 'statsk:index' %}">Statistik</a>
                </li>
                <li class="nav-item {{ faq_stats }}">
                <a class="nav-link" href="{% url 'faq' %}">FAQ</a>
                </li>
                <li class="nav-item {{ tutorial_stats }}">
                <a class="nav-link" href="{% url 'tutorial' %}">Tutorial</a>
                </li>
                
                {% if user.is_authenticated %}
                <li class="nav-item {{ profile_stats }}">
                    <a class="nav-link" href="{% url 'accmgr:profile' %}">Profile</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/new_tutorial.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
{% include 'new_navbar.html' with tutorial_stats='active' %}
{% endblock %}

{% block includedcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_tutorial.css' %}">
{% endblock %}
    
{% block content %}
<div class="header">
    <div class="container">
        <h1>TUTORIAL</h1>
    </div>
</div>

<div class="container faq-block"> 
    <div class="faq-content">
        <h2>1. DAFTARKAN DIRIMU DI WEBSITE KAMI</h2>
        <p>
            Dengan bergabung bersama kami, kamu bisa ikut andil dalam 
            mewujudkan dunia yang lebih baik dari sebelumnya.
        </p>
    </div>

    <div class="faq-content">
        <h2>2. DAFTARKAN SAMPAHMU</h2>
        <p>
            Pengguna dapat mendaftarkan berat dan jenis 
            sampahnya, lalu menunggu konfirmasi penjemputan oleh mitra kami.
            <br>
            Pendaftaran dapat melalui halaman
            <span><a href="#" style="color: #76B39D;">Buang Sampah</a></span>
        </p>
    </div>

    <div class="faq-content">
        <h2>3. PENJEMPUTAN GRATIS</h2>
        <p>
            Mitra kami akan datang untuk mengambil 
            sampah sesuai konfirmasi tempat dan tanggal penjemputan.
        </p>
    </div>

    <div class="faq-content">
        <h2>4. DAPATKAN UANG</h2>
        <p>
            Pengguna akan mendapatkan uang dari sampah yang mereka buang dan akan tersimpan di
            <b style="color: #155E63;">Dompetku</b>.
        </p>
    </div>
</div>
{% endblock %}
    